from scipy.io import loadmat
import matplotlib.pyplot as plt
import glob
import csv
import class_LossHistory
import numpy as np
import pandas as pd
import datatable as dt
import math
import os
from tensorflow import keras
from tensorflow.keras.layers import *
from tensorflow.keras.models import *
#from keras.objectives import *

Data_DIR = "MSI/data/MSINorm-all-CRC.csv"
# The normalized data can be generated by main_Cluster_CRCglycan.py
CSV_DIR = "MSI/data/MSIbiaozhuNPArray_CRCglycan_manual_improved.csv"
MANIFEST_DIR = "MSI/data/MSIbiaozhuShuffle_CRCglycan_manual.csv"
CLASS_NUM = 3
IS_MANUAL_LABEL = True

sample_num = 0
Batch_size = 150
#打开CSV数据文件，
def load_data_csv(Data_DIR=Data_DIR):
    my_table = dt.fread(Data_DIR, sep=",", header=False)  ## datatable格式读取文件
    data = my_table.to_numpy()      ## datatable格式转np数组，保存int数据
    print(data.shape)
    return data

#把标签转成oneHot形式
def convert2oneHot(index,classNum):
    hot = np.zeros((classNum,))
    hot[index-1] = 1
    return hot

#数据要变成(参数数量, 1)的形状
def convertdatashape(data, num):
    return np.array([data[num]]).T

#标签处理方式

def create_3label_csv(CSV_DIR=CSV_DIR):
    lists = pd.read_csv(CSV_DIR, sep=r",", header=None)
    lists[lists[0].isin([0])] = 1   #把标签0改为1
    lists = lists[lists[0].isin([1, 2, 3])]     #提取1，2，3标签重做list
    lists = lists.sample(frac=1)             #随机打乱list中的样本
    lists.to_csv(MANIFEST_DIR, index=1, header=None)  #保存打乱后的CSV文件，所有选取样本的原始行索引会输出，index=1
    print(lists.value_counts())      #打印所有标签的样本数
    print("Finish save csv")

def create_4label_csv(CSV_DIR=CSV_DIR):
    lists = pd.read_csv(CSV_DIR, sep=r",", header=None)
    lists = lists[lists[0].isin([0, 1, 2, 3])]     # 提取0, 1，2，3标签重做list
    lists = lists.sample(frac=1)             # 随机打乱list中的样本
    lists.to_csv(MANIFEST_DIR, index=1, header=None)  # 保存打乱后的CSV文件，所有选取样本的原始行索引会输出，index=1
    print(lists.value_counts())      # 打印所有标签的样本数
    print("Finish save csv")

def create_3label_manual_csv(CSV_DIR=CSV_DIR):
    lists = pd.read_csv(CSV_DIR, sep=r",", header=None)
    # manual label标签只包含1,2,3，因为0值是不在stained image区域内只在cluster label中有
    lists = lists[lists[0].isin([1, 2, 3])]     #提取1，2，3标签重做list
    lists = lists.sample(frac=1)             #随机打乱list中的样本
    lists.to_csv(MANIFEST_DIR, index=1, header=None)  #保存打乱后的CSV文件，所有选取样本的原始行索引会输出，index=1
    print(lists.value_counts())      #打印所有标签的样本数
    print("Finish save csv")

#数据迭代方式

def xs_gen(data, biaozhu_path=MANIFEST_DIR, batch_size = Batch_size,train=True):

    img_list = pd.read_csv(biaozhu_path).to_numpy().astype(np.uint32)
    print(img_list.shape)
    if train:
        img_list = img_list[:math.ceil(sample_num/10*9)]
        print("Found %s train items." % len(img_list))
        print("list 1 is", img_list[0])
        steps = math.ceil(len(img_list) / batch_size)    # 确定每轮有多少个batch
    else:
        img_list = img_list[math.ceil(sample_num/10*9):]
        print("Found %s test items." % len(img_list))
        print("list 1 is", img_list[0])
        steps = math.ceil(len(img_list) / batch_size)    # 确定每轮有多少个batch
    while True:
        np.random.shuffle(img_list)
        for i in range(steps):
            batch_list = img_list[i * batch_size: i * batch_size + batch_size]
            np.random.shuffle(batch_list)
            batch_x = np.array([convertdatashape(data, num) for num in batch_list[:, 0]])
            batch_y = np.array([convert2oneHot(label, CLASS_NUM) for label in batch_list[:, 1]])
            yield batch_x, batch_y

#模型搭建
def build_model(input_shape,num_classes):
    model = Sequential()
    model.add(Conv1D(filters=16, kernel_size=16,strides=2, activation='relu', input_shape=input_shape))
    model.add(Conv1D(filters=16, kernel_size=16,strides=2, activation='relu', padding="same"))
    model.add(MaxPooling1D(2))
    model.add(Conv1D(filters=64, kernel_size=8,strides=2, activation='relu', padding="same"))
    model.add(Conv1D(filters=64, kernel_size=8,strides=2, activation='relu', padding="same"))
    model.add(MaxPooling1D(2))
    model.add(Conv1D(filters=128, kernel_size=4,strides=2, activation='relu', padding="same"))
    model.add(Conv1D(filters=128, kernel_size=4,strides=2, activation='relu', padding="same"))
    model.add(MaxPooling1D(2))
    model.add(Conv1D(filters=256, kernel_size=2,strides=1, activation='relu', padding="same"))
    model.add(Conv1D(filters=256, kernel_size=2,strides=1, activation='relu', padding="same"))
    model.add(MaxPooling1D(2))
    model.add(GlobalAveragePooling1D())
    model.add(Dropout(0.3))
    model.add(Dense(num_classes, activation='softmax'))
    return(model)

#模型训练
if __name__ == "__main__":

    if not os.path.exists(MANIFEST_DIR):
        if CLASS_NUM == 3 and IS_MANUAL_LABEL==True:
            create_3label_manual_csv()
        elif CLASS_NUM == 3 and IS_MANUAL_LABEL==False:
            create_3label_csv()
        elif CLASS_NUM == 4:
            create_4label_csv()
    img_list = pd.read_csv(MANIFEST_DIR)
    sample_num = len(img_list)

    os.environ["CUDA_VISIBLE_DEVICES"] = "0"

    data = load_data_csv()

    train_iter = xs_gen(train=True, data=data)
    test_iter = xs_gen(train=False, data=data)
    model = build_model(input_shape=(data.shape[1], 1), num_classes=CLASS_NUM)
    print(model.summary())

    initial_learning_rate = 0.0001
    lr_schedule = keras.optimizers.schedules.ExponentialDecay(
        initial_learning_rate, decay_steps=100000, decay_rate=0.96, staircase=True
    )
    model.compile(
        loss="binary_crossentropy",
        optimizer=keras.optimizers.Adam(learning_rate=lr_schedule),
        metrics=["acc"],
    )

    ckpt = keras.callbacks.ModelCheckpoint(
        filepath='msi_1dcnn_best_model.{epoch:02d}-{val_acc:.2f}.h5',
        monitor='val_acc', save_best_only=True, verbose=1)

    tensorboard_cb = keras.callbacks.TensorBoard(
        log_dir='my_log_dir',
        histogram_freq=0,
        embeddings_freq=0,
        #update_freq='batch'
    )

    logs_loss = class_LossHistory.LossHistory()

    model.fit_generator(
        generator=train_iter,
        steps_per_epoch=math.ceil(sample_num/10*9)//Batch_size,
        epochs=50,
        initial_epoch=0,
        validation_data=test_iter,
        # keras 2之下的版本 nb_val_samples = 100//Batch_size,
        validation_steps=(sample_num-math.ceil(sample_num/10*9))//Batch_size,
        callbacks=[ckpt, tensorboard_cb, logs_loss],
        )

    #作图
    logs_loss.end_draw()

