import class_Cluster_Method
import class_Decomposition_Method
import matplotlib.pyplot as plt
import numpy as np
import datatable as dt
import csv
import os
from time import time

sampleNum = 34840
featureNum = 92064
pixelNumX = 260
pixelNumY = 134
def get_feature(csv_file_num):
    # The normalized data can be generated by main_Preprocessing_HR2MSI.py
    BASE_DIR = "MSI/result/HR2MSI/"
    file = "lxml" + str(csv_file_num) + "(" + str(csv_file_num // pixelNumX) + ',' + str(csv_file_num % pixelNumX) + ')' + '.csv'
    my_table = dt.fread(BASE_DIR + file, sep=",", header=False)
    ints = my_table.to_numpy()
    return ints

def load_data_separatedCSV():
    data = np.zeros((sampleNum, featureNum), dtype=np.uint8)
    for i in range(sampleNum):
        data[i, :] = get_feature(i)[:, 0].astype(np.uint8)
    return data

def load_data_oneCSV():
    file = "MSI/data/MSINorm-all.csv"
    # The normalized data can be downloaded from: https://pan.baidu.com/s/1GnCpK08nGifOkyB9koYF0A?pwd=ugv8
    my_table2 = dt.fread(file, sep=",", header=False)
    data2 = my_table2.to_numpy().astype(np.uint32)
    return data2

if __name__ == "__main__":
    cluster = class_Cluster_Method.ClusterMethod
    decomposition = class_Decomposition_Method.DecompositionMethod
    n_components = 2  # dimension =2
    decomposition_method = 'decomposite_data_tSNE'
    # 'decomposite_data_tSNE'    n_components <= 3
    # 'decomposite_data_NMF'
    # 'decomposite_data_PCA'
    # 'decomposite_data_None'
    n_clusters = 3     # k=3
    cluster_method = 'model_HC_Agglomerative'
    # 'model_HC_Agglomerative'
    # 'model_kmeans'
    file = "MSI/data/"+decomposition_method+str(n_components)+".csv"
    numoftimes = 1
    y_Predicted_nparray = np.zeros((34840, numoftimes))
    y_Predicted = np.array((34840,))
    for i in range(numoftimes):
        t0 = time()
        if not os.path.exists(file):
            data = load_data_separatedCSV()
            t1 = time()
            dataReduced = getattr(decomposition, decomposition_method)(decomposition, data, n_components)
            t2 = time()
            y_Predicted = getattr(cluster, cluster_method)(cluster, dataReduced, n_clusters)
        else:
            my_table = dt.fread(file, sep=",", header=False)
            t1 = time()
            dataReduced = my_table.to_numpy()
            t2 = time()
            y_Predicted = getattr(cluster, cluster_method)(cluster, dataReduced, n_clusters)
        t3 = time()
        print('time,', t1-t0, ',', t2-t1, ',', t3-t2, ',', i)
        y_Predicted_nparray[:, i] = y_Predicted
        # cluster figure save and show
        plt.figure(figsize=(8,5), dpi=100)
        plt.axis('off')
        plt.xticks([])
        plt.yticks([])
        plt.scatter([x for x in range(pixelNumX)]*pixelNumY,
                    [y for y in range(pixelNumY-1 ,-1 ,-1) for i in range(pixelNumX)],
                    c=y_Predicted,
                    s=1,
                    cmap='magma'
                    )
        plt.savefig("MSI/result/HR2MSI/clustering/color" + str(i) + "_" + cluster_method + "_" + str(n_clusters) + ".jpg",
                    dpi=300,
                    bbox_inches='tight',
                    pad_inches=-0.01)
        plt.show()
    # save cluster result
    with open("MSI/result/HR2MSI/clustering/clusterbiaozhu.csv", 'w', encoding='utf-8', newline="") as f:
        for i in range(len(y_Predicted_nparray)):
            csv_write = csv.writer(f)
            csv_write.writerow(y_Predicted_nparray[i])